### ISSUE TITLE
Given a range, the copy-history command raise a NoMethodError

### ISSUE THREAD

**Issue by mkelley33** [hotchpotch/pry-clipboard#2]
After installing ruby-2.0.0-p0 and Rails 4.0.0.beta1, I received the following error:

```
Loading development environment (Rails 4.0.0.beta1)
[1] 2.0.0-p0(main)> copy-history -R 10..12
NoMethodError: undefined method `<' for true:TrueClass
from /usr/local/rvm/gems/ruby-2.0.0-p0/gems/pry-0.9.12/lib/pry/code/code_range.rb:49:in        
`find_start_index'
```

I've tried installing the latest tag (v0.5.0.pre.1) of **rb-readline**, but I still received the same error message.  I'm using **wemux** (tmux) on Mac OS X (10.8.3 Mountain Lion)  In previous versions of ruby and rails `copy-history -R 10..12` has worked without any error. However, I had to edit my **~/tmux.conf** so that `copy-history` would work with ruby-1.9.3 and rails 3.2.13 like so:

```
# OSX Clipboard support
source ~/.tmux.clipboard
bind C-v run "tmux set-buffer $(reattach-to-user-namespace pbpaste); tmux paste-buffer"
bind C-c run "tmux save-buffer - | reattach-to-user-namespace pbcopy"
```
